/*
 * PUS task — TC dispatch and service handlers S1/S8/S17/S20.
 *
 * This task owns the TC dispatcher and all PUS service contexts. It blocks
 * on the TC frame queue produced by the TMTC task, applies the FDIR FSM TC
 * gate, dispatches allowed frames, and notifies the TMTC task to drain any
 * TM packets generated by the handlers.
 *
 * FSM TC gate (SAFE mode):
 *   Before feeding the dispatcher, the raw frame is checked against the FSM
 *   whitelist. Non-whitelisted TCs are silently dropped in SAFE mode. The
 *   whitelist (S8/S17/S20-get) is configured by the FDIR task.
 *   Frame byte offsets: service = frame[12], subservice = frame[13].
 *   (5-byte TC transfer frame header + 6-byte space packet primary header +
 *    1-byte PUS version/ack = byte 12 for service type.)
 */

#include "obsw/task/pus.h"
#include "obsw/task/tmtc.h"
#include "obsw/pus/pus_tm.h"
#include "obsw/pus/s1.h"
#include "obsw/pus/s8.h"
#include "obsw/pus/s17.h"
#include "obsw/pus/s20.h"
#include "obsw/tc/dispatcher.h"
#include "obsw/ccsds/tc_frame.h"
#include "obsw/ccsds/space_packet.h"
#include "obsw/srdb_generated.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"

#define PUS_STACK_DEPTH 512U
#define PUS_PRIORITY    3U   /* Med-high — TC processing */

/* Byte offsets in raw TC frame for FSM gate check.
 * TC transfer frame header (5) + space packet primary header (6) +
 * PUS secondary header version/ack byte (1) = service at byte 12. */
#define FRAME_SVC_OFFSET    12U
#define FRAME_SUBSVC_OFFSET 13U
#define FRAME_GATE_MIN_LEN  14U

/* ── PUS service state ────────────────────────────────────────────── */

static obsw_s1_ctx_t  s1_ctx  = {0};
static obsw_s17_ctx_t s17_ctx = {0};
static obsw_s20_ctx_t s20_ctx = {0};
static obsw_s8_ctx_t  s8_ctx  = {0};

static obsw_s20_param_t s20_params[] = {
    {.param_id = SRDB_PARAM_OBC_UPTIME,            .value = {.u32 = 0}},
    {.param_id = SRDB_PARAM_SAFE_MODE_ENTRY_COUNT, .value = {.u32 = 0}},
    {.param_id = SRDB_PARAM_WATCHDOG_KICK_COUNT,   .value = {.u32 = 0}},
};

/* S8 function table — recover_nominal calls fsm_to_nominal on the FDIR FSM. */
static int recover_nominal(const uint8_t *args, uint8_t args_len, void *ctx)
{
    (void)args; (void)args_len;
    obsw_fsm_to_nominal((obsw_fsm_ctx_t *)ctx);
    return 0;
}

static obsw_s8_entry_t s8_table[] = {
    {.function_id = OBSW_S8_FN_RECOVER_NOMINAL, .fn = recover_nominal, .ctx = NULL},
};

static obsw_tc_route_t s_routes[] = {
    {.apid = 0xFFFF, .service = 8,  .subservice = 1,
     .handler = obsw_s8_perform, .ctx = &s8_ctx},
    {.apid = 0xFFFF, .service = 17, .subservice = 1,
     .handler = obsw_s17_ping,   .ctx = &s17_ctx},
    {.apid = 0xFFFF, .service = 20, .subservice = 1,
     .handler = obsw_s20_set,    .ctx = &s20_ctx},
    {.apid = 0xFFFF, .service = 20, .subservice = 3,
     .handler = obsw_s20_get,    .ctx = &s20_ctx},
};

static obsw_tc_dispatcher_t s_dispatcher;

/* ── Task state ───────────────────────────────────────────────────── */

static StaticTask_t  s_tcb;
static StackType_t   s_stack[PUS_STACK_DEPTH];

static QueueHandle_t   s_tc_queue;
static TaskHandle_t    s_tmtc_handle;
static obsw_fsm_ctx_t *s_fsm;

/* ── Helpers ──────────────────────────────────────────────────────── */

static void noop_responder(uint8_t flag, const obsw_tc_t *tc, void *ctx)
{
    (void)flag; (void)tc; (void)ctx;
}

/* ── Task body ────────────────────────────────────────────────────── */

static void pus_task(void *param)
{
    (void)param;

    obsw_tc_frame_item_t item;

    for (;;) {
        if (xQueueReceive(s_tc_queue, &item, portMAX_DELAY) != pdTRUE)
            continue;

        /* FSM TC gate: drop non-whitelisted TCs in SAFE mode. */
        if (item.len >= FRAME_GATE_MIN_LEN &&
            !obsw_fsm_tc_allowed(s_fsm,
                                 item.data[FRAME_SVC_OFFSET],
                                 item.data[FRAME_SUBSVC_OFFSET])) {
            continue; /* silently drop — ground detects missing S1(1,1) */
        }

        obsw_tc_dispatcher_feed(&s_dispatcher, item.data, item.len);

        /* Wake TMTC to drain any TM we just produced. */
        xTaskNotify(s_tmtc_handle, 0, eNoAction);
    }
}

/* ── Public API ───────────────────────────────────────────────────── */

void obsw_pus_task_init(obsw_tm_store_t *tm_store,
                        QueueHandle_t    tc_queue,
                        TaskHandle_t     tmtc_handle,
                        obsw_fsm_ctx_t  *fsm)
{
    s_tc_queue    = tc_queue;
    s_tmtc_handle = tmtc_handle;
    s_fsm         = fsm;

    s1_ctx.tm_store    = tm_store;
    s1_ctx.apid        = SRDB_APID_DEFAULT;
    s1_ctx.msg_counter = 0;
    s1_ctx.timestamp   = 0;

    s17_ctx.tm_store    = tm_store;
    s17_ctx.s1          = &s1_ctx;
    s17_ctx.apid        = SRDB_APID_DEFAULT;
    s17_ctx.msg_counter = 0;
    s17_ctx.timestamp   = 0;

    s20_ctx.tm_store  = tm_store;
    s20_ctx.s1        = &s1_ctx;
    s20_ctx.apid      = SRDB_APID_DEFAULT;
    s20_ctx.table     = s20_params;
    s20_ctx.table_len = sizeof(s20_params) / sizeof(s20_params[0]);

    s8_table[0].ctx   = fsm;  /* recover_nominal callback receives FSM ptr */
    s8_ctx.tm_store   = tm_store;
    s8_ctx.s1         = &s1_ctx;
    s8_ctx.apid       = SRDB_APID_DEFAULT;
    s8_ctx.table      = s8_table;
    s8_ctx.table_len  = sizeof(s8_table) / sizeof(s8_table[0]);

    obsw_tc_dispatcher_init(&s_dispatcher,
                             s_routes,
                             sizeof(s_routes) / sizeof(s_routes[0]),
                             noop_responder, NULL);

    xTaskCreateStatic(pus_task, "PUS", PUS_STACK_DEPTH,
                      NULL, PUS_PRIORITY, s_stack, &s_tcb);
}
