"""
sim/wire_proto.py — Wire protocol v3 helpers shared by openobsw harnesses.

Frame format (framed pipe over stdin/stdout):
  → OBSW  0x01 [uint16 BE len] [TC space packet bytes]   TC uplink
  → OBSW  0x02 [uint16 BE len] [obsw_sensor_frame_t]     Sensor injection
  ← OBSW  0x03 [uint16 BE len] [obsw_actuator_frame_t]   Actuator output
  ← OBSW  0x04 [uint16 BE len] [TM space packet bytes]   TM downlink
  ← OBSW  0xFF                                            End-of-tick

PUS TM secondary header layout (11 bytes at offset 6):
  [6]     PUS version
  [7]     service
  [8]     subservice
  [9-10]  msg_counter (BE)
  [11-12] dest_id (BE)
  [13-16] timestamp (BE)
  [17+]   application data

S20 TM(20,2) application data (6 bytes at offset 17):
  [17-18] param_id (BE uint16)
  [19-22] value    (BE uint32 / IEEE 754 float)
"""

import struct
import numpy as np

# ── Wire protocol constants ───────────────────────────────────────────────
FRAME_TC     = 0x01
FRAME_SENSOR = 0x02
FRAME_ACT    = 0x03
FRAME_TM     = 0x04
SYNC_EOT     = 0xFF

APID_DEFAULT = 0x010

SENSOR_LEN = 47
ACTUAT_LEN = 29
SENSOR_FMT = '<fffBffffBfffBf'   # 47 bytes
ACTUAT_FMT = '<ffffffBf'         # 29 bytes

# ── SRDB parameter IDs (mirrors srdb/data/parameters.yaml) ───────────────
SRDB_BDOT_GAIN             = 0x20A0
SRDB_ADCS_KP               = 0x20A1
SRDB_ADCS_KD               = 0x20A2
SRDB_ORBIT_ALTITUDE_KM     = 0x3001
SRDB_ORBIT_INCLINATION_DEG = 0x3002
SRDB_SC_INERTIA_XX         = 0x3010
SRDB_SC_INERTIA_YY         = 0x3011
SRDB_SC_INERTIA_ZZ         = 0x3012
SRDB_MTQ_MAX_DIPOLE        = 0x3020
SRDB_SC_OMEGA_X0           = 0x3030
SRDB_SC_OMEGA_Y0           = 0x3031
SRDB_SC_OMEGA_Z0           = 0x3032

# PUS TM offsets
_TM_SVC_OFF  = 7    # body[7] = service
_TM_SUBSVC_OFF = 8  # body[8] = subservice
_TM_BODY_OFF = 17   # body[17+] = application data (after 6-byte primary + 11-byte sec hdr)


# =========================================================================
# Low-level I/O
# =========================================================================

def read_exact(f, n):
    """Blocking read of exactly n bytes from file-like f."""
    data = b''
    while len(data) < n:
        chunk = f.read(n - len(data))
        if not chunk:
            raise EOFError('sim stdout closed unexpectedly')
        data += chunk
    return data


# =========================================================================
# TC helpers
# =========================================================================

def build_tc(apid, svc, subsvc, data=b''):
    """Build a PUS-C TC space packet (no TC Transfer Frame wrapper)."""
    pkt_len = 6 + 5 + len(data)
    hdr = struct.pack('>HHH',
        0x1800 | (apid & 0x7FF),
        0xC000,
        pkt_len - 7,
    )
    sec = bytes([0x20, svc, subsvc, 0x00, 0x00])
    return hdr + sec + data


def send_tc(proc, tc_bytes):
    """Send a TC wrapped in wire protocol v3 type-0x01 frame."""
    proc.stdin.write(bytes([FRAME_TC]) + struct.pack('>H', len(tc_bytes)) + tc_bytes)
    proc.stdin.flush()


def drain_tc_response(proc):
    """Discard all TM packets + EOT generated by a TC — no parsing."""
    while True:
        ftype = read_exact(proc.stdout, 1)[0]
        if ftype == SYNC_EOT:
            return
        flen = struct.unpack('>H', read_exact(proc.stdout, 2))[0]
        read_exact(proc.stdout, flen)


# =========================================================================
# Sensor / actuator frames
# =========================================================================

def send_sensor(proc, B_body, q, omega, t, *,
                mag_valid=1, st_valid=1, gyro_valid=1):
    """Pack and send a type-0x02 sensor frame.

    Args:
        B_body:     [3] magnetic field in body frame [T]
        q:          [4] quaternion [w,x,y,z] body→ECI
        omega:      [3] angular velocity in body frame [rad/s]
        t:          simulation clock [s]
        mag_valid:  1 if magnetometer reading is valid
        st_valid:   1 if star tracker reading is valid
        gyro_valid: 1 if gyro reading is valid
    """
    payload = struct.pack(SENSOR_FMT,
        float(B_body[0]), float(B_body[1]), float(B_body[2]), int(mag_valid),
        float(q[0]),      float(q[1]),      float(q[2]),      float(q[3]), int(st_valid),
        float(omega[0]),  float(omega[1]),  float(omega[2]),  int(gyro_valid),
        float(t),
    )
    proc.stdin.write(bytes([FRAME_SENSOR]) + struct.pack('>H', len(payload)) + payload)
    proc.stdin.flush()


class ActuatorFrame:
    """Parsed obsw_actuator_frame_t."""
    __slots__ = ['mtq', 'rw_torque', 'controller', 'sim_time']

    def __init__(self):
        self.mtq        = np.zeros(3)   # [Am²]
        self.rw_torque  = np.zeros(3)   # [N·m]
        self.controller = 0             # 0=bdot, 1=PD ADCS
        self.sim_time   = 0.0           # [s]


def recv_tick(proc):
    """
    Drain one complete tick from sim stdout (up to and including 0xFF EOT).
    Returns ActuatorFrame (zeros if no 0x03 frame received this tick).
    TM packets (0x04) are discarded.
    """
    act = ActuatorFrame()
    while True:
        ftype = read_exact(proc.stdout, 1)[0]
        if ftype == SYNC_EOT:
            return act
        flen    = struct.unpack('>H', read_exact(proc.stdout, 2))[0]
        payload = read_exact(proc.stdout, flen)
        if ftype == FRAME_ACT and len(payload) == ACTUAT_LEN:
            v = struct.unpack(ACTUAT_FMT, payload)
            act.mtq        = np.array([v[0], v[1], v[2]])
            act.rw_torque  = np.array([v[3], v[4], v[5]])
            act.controller = v[6]
            act.sim_time   = v[7]


# =========================================================================
# Shared attitude dynamics helpers (used by bdot_harness and adcs_harness)
# =========================================================================

def quat_step(q, omega, dt):
    """First-order quaternion kinematic update. q̇ = ½ q ⊗ [0, ω]."""
    w, x, y, z = q
    ox, oy, oz = omega
    dq = 0.5 * np.array([
        -x*ox - y*oy - z*oz,
         w*ox + y*oz - z*oy,
         w*oy - x*oz + z*ox,
         w*oz + x*oy - y*ox,
    ])
    q_new = q + dt * dq
    return q_new / np.linalg.norm(q_new)


def omega_step(omega, torque, I, I_inv, dt):
    """Euler rigid-body step. I·ω̇ = τ − ω × (I·ω)."""
    I_omega = I @ omega
    return omega + dt * (I_inv @ (torque - np.cross(omega, I_omega)))


# =========================================================================
# S20 parameter access
# =========================================================================

def query_s20_float(proc, param_id, default=0.0, apid=APID_DEFAULT):
    """
    Send TC(20,3) get-parameter and parse TM(20,2) response.

    Returns the float value stored in the OBSW, or `default` if the param
    was not found or the response did not arrive.

    TM(20,2) layout (23 bytes total):
      [0-5]   primary header
      [6]     PUS version
      [7]     service=20
      [8]     subservice=2
      [9-12]  msg_counter + dest_id
      [13-16] timestamp
      [17-18] param_id (BE uint16)
      [19-22] value    (BE float32)
    """
    send_tc(proc, build_tc(apid, 20, 3, struct.pack('>H', param_id)))
    result = default
    while True:
        ftype = read_exact(proc.stdout, 1)[0]
        if ftype == SYNC_EOT:
            break
        flen    = struct.unpack('>H', read_exact(proc.stdout, 2))[0]
        payload = read_exact(proc.stdout, flen)
        if (ftype == FRAME_TM
                and len(payload) >= 23
                and payload[_TM_SVC_OFF]   == 20
                and payload[_TM_SUBSVC_OFF] == 2):
            pid = struct.unpack('>H', payload[17:19])[0]
            if pid == param_id:
                result = struct.unpack('>f', payload[19:23])[0]
    return result
