"""
codegen.py — Generate srdb_generated.h from the SRDB YAML data.

This script is called by CMake at build time to produce:
    build/include/obsw/srdb_generated.h

The generated header provides named C constants for parameter IDs,
event IDs, and HK set IDs — eliminating magic numbers in C code.

Usage (CLI):
    python3 codegen.py --data-dir srdb/data --output build/include/obsw/srdb_generated.h

Usage (Python API):
    from obsw_srdb.codegen import generate_header
    header = generate_header(srdb)
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from .loader import SRDBLoader
from .model import SRDB


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def generate_header(srdb: SRDB) -> str:
    """Return the content of srdb_generated.h as a string."""
    lines = [
        "/**",
        " * @file srdb_generated.h",
        " * @brief Auto-generated SRDB constants — DO NOT EDIT.",
        " *",
        f" * Mission: {srdb.spacecraft.name}",
        f" * SCID:    0x{srdb.spacecraft.scid:03X}",
        " *",
        " * Generated by openobsw/srdb/obsw_srdb/codegen.py",
        " * Source:   srdb/data/*.yaml",
        " */",
        "#ifndef OBSW_SRDB_GENERATED_H",
        "#define OBSW_SRDB_GENERATED_H",
        "",
        "#include <stdint.h>",
        "",
    ]

    # ---- Mission identity --------------------------------------------------
    lines += [
        "/* ---------------------------------------------------------------- */",
        "/* Mission                                                          */",
        "/* ---------------------------------------------------------------- */",
        "",
        f"#define SRDB_SPACECRAFT_NAME  \"{srdb.spacecraft.name}\"",
        f"#define SRDB_SCID             0x{srdb.spacecraft.scid:03X}U",
        f"#define SRDB_APID_DEFAULT     0x{srdb.spacecraft.apid_default:03X}U",
        "",
    ]

    # ---- Parameters --------------------------------------------------------
    lines += [
        "/* ---------------------------------------------------------------- */",
        "/* Parameter IDs                                                    */",
        "/* ---------------------------------------------------------------- */",
        "",
    ]
    for p in srdb.parameters:
        macro = f"SRDB_PARAM_{p.name.upper()}"
        lines.append(f"#define {macro:<40s} 0x{p.id:04X}U  /**< {p.description} */")
    lines.append("")

    # ---- Events ------------------------------------------------------------
    lines += [
        "/* ---------------------------------------------------------------- */",
        "/* Event IDs                                                        */",
        "/* ---------------------------------------------------------------- */",
        "",
    ]
    for e in srdb.events:
        macro = f"SRDB_EVENT_{e.name.upper()}"
        trigger = " [safe-trigger]" if e.safe_trigger else ""
        lines.append(
            f"#define {macro:<40s} 0x{e.id:04X}U"
            f"  /**< [{e.severity.value}]{trigger} {e.description} */"
        )
    lines.append("")

    # ---- HK set IDs --------------------------------------------------------
    lines += [
        "/* ---------------------------------------------------------------- */",
        "/* HK Set IDs                                                       */",
        "/* ---------------------------------------------------------------- */",
        "",
    ]
    for h in srdb.hk_sets:
        macro = f"SRDB_HK_{h.name.upper()}"
        lines.append(
            f"#define {macro:<40s} {h.id}U"
            f"  /**< {h.description} (default interval: {h.default_interval_ticks} ticks) */"
        )
    lines.append("")

    # ---- Safe-trigger event ID array (C99 compound literal helper) ---------
    safe_ids = srdb.safe_trigger_event_ids()
    lines += [
        "/* ---------------------------------------------------------------- */",
        "/* Safe-trigger event IDs (for obsw_s5_ctx_t initialisation)       */",
        "/* ---------------------------------------------------------------- */",
        "",
        f"#define SRDB_SAFE_TRIGGER_COUNT  {len(safe_ids)}U",
        "",
    ]
    if safe_ids:
        id_list = ", ".join(f"0x{eid:04X}U" for eid in safe_ids)
        lines += [
            "/** Initialiser for obsw_s5_ctx_t.safe_trigger_ids[] */",
            f"#define SRDB_SAFE_TRIGGER_IDS  {{ {id_list} }}",
            "",
        ]

    # ---- Telecommand routing helpers ---------------------------------------
    lines += [
        "/* ---------------------------------------------------------------- */",
        "/* Telecommand routing                                              */",
        "/* ---------------------------------------------------------------- */",
        "",
    ]
    for tc in srdb.telecommands:
        prefix = f"SRDB_TC_{tc.name.upper()}"
        lines += [
            f"#define {prefix + '_APID':<48s} 0x{tc.apid:03X}U",
            f"#define {prefix + '_SVC':<48s} {tc.service}U",
            f"#define {prefix + '_SUBSVC':<48s} {tc.subservice}U",
        ]
    lines.append("")

    lines += [
        "#endif /* OBSW_SRDB_GENERATED_H */",
        "",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI entry point (called by CMake)
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate srdb_generated.h from SRDB YAML data."
    )
    parser.add_argument(
        "--data-dir", required=True,
        help="Path to srdb/data/ directory containing YAML files"
    )
    parser.add_argument(
        "--output", required=True,
        help="Output path for srdb_generated.h"
    )
    args = parser.parse_args()

    srdb = SRDBLoader.load(args.data_dir)
    header = generate_header(srdb)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(header)

    print(f"[srdb codegen] wrote {output_path}")


if __name__ == "__main__":
    main()